services:
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    working_dir: /workspace
    volumes:
      - ..:/workspace
    command: bash

  k6:
    image: grafana/k6:0.46.0
    working_dir: /workspace
    volumes:
      - ..:/workspace
    entrypoint: ["k6"]
    command: ["version"]
